### ISSUE TITLE
"Issues" forum for vendors

### ISSUE THREAD

**Issue by randyhart** [18F/acq-alaska-dhss-modernization#30]
As a procurement team, we'd like to have an "issues" tab that's focused on gathering feedback/questions from vendors on the broader procurement strategy, so that we can understand have a transparent way of gathering feedback that can be shared with the broader community of interested vendors.  

I think this should be housed within https://github.com/18F/acq-alaska-dhss-modernization/tree/master/vendor-info but I'm open to whatever makes the most sense from a design/clarity perspective.

**Comment by mheadd** [comment]
So based on our discussions, it seems like the best approach is for each solicitation to be contained within it's own separate Github repository. That way, vendors that have questions can open issues in a project-specific repo, and AK can also use [issues](https://guides.github.com/features/issues/) to dialog on topics relevant to the buy.

We can simply link to these separate repos from the README file in the [vendor info directory](https://github.com/18F/acq-alaska-dhss-modernization/tree/master/vendor-info), so that there is a centralized list in this overarching project repository. Or, alternatively, we can include the separate repos for each solicitation as [submodules](https://github.com/blog/2104-working-with-submodules) within the `vendor-info` directory.

Simply adding links in the README file in the `vendor-info` directory is probably the easiest approach, and should be sufficient for the first buy.

**Comment by randyhart** [comment]
Making new repos for future procurements, linked to the README of `vendor-info` from this Repo, makes the most sense to me.  

I'd like to also make sure vendors know to submit `issues` if they have questions/suggestions about the overarching procurement strategy and/or Alaska's environment.  Would it make most sense for them to just use the `issues` tab on acq-alaska-dhss-modernization and then just label it with `vendor comment` or `vendor feedback`?

**Comment by mheadd** [comment]
That makes sense to me.

If a vendor makes a comment in a project specific repo that relates to the overarching strategy or a related issue, we can direct them to this repo and have them create (or link to) an issue here. We can also add [those labels](https://github.com/18F/acq-alaska-dhss-modernization/labels) in this repo's issues listing to filter comments like those.

**Comment by edmullen** [comment]
I had previously pushed for submodules for each procurement, but with our discussions about VSTS --> Github syncing, I know agree it's probably best to just make separate repos and link them as Mark said. That creates fewer dependencies.

**Comment by randyhart** [comment]
Thanks for helping sort this out.  I agree. @jongeselle if you agree with this approach, please feel free to close this issue so we know it's resolved.

**Comment by jongeselle** [comment]
Yes. I think this approach makes a great deal of sense. I'll go ahead and close this one.
